CREATE OR REPLACE TABLE STAGING.STG_PATIENT (
    PATIENT_ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    GENDER STRING,
    DATE_OF_BIRTH DATE,
    UPDATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE STAGING.STG_INSURANCE (
    INSURANCE_ID INT,
    PATIENT_ID INT,
    PROVIDER STRING,
    PLAN STRING,
    UPDATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE STAGING.STG_HEALTH_CONDITION (
    CONDITION_ID INT,
    PATIENT_ID INT,
    CONDITION_NAME STRING,
    DIAGNOSIS_DATE DATE,
    UPDATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE STAGING.STG_HCP (
    HCP_ID INT,
    PATIENT_ID INT,
    NAME STRING,
    SPECIALITY STRING,
    UPDATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE STAGING.STG_HCO (
    HCO_ID INT,
    PATIENT_ID INT,
    NAME STRING,
    LOCATION STRING,
    UPDATED_AT TIMESTAMP
);
