-- Create internal stage
CREATE OR REPLACE STAGE HEALTHCARE_STAGE;

---file format---
CREATE OR REPLACE FILE FORMAT HELATHCARE_CSV_FORMAT
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1;



ALTER STAGE HEALTHCARE_STAGE SET DIRECTORY = (ENABLE = TRUE);

---for checking_stage---
SELECT RELATIVE_PATH, LAST_MODIFIED
FROM DIRECTORY(@HEALTHCARE_STAGE);

SHOW STAGES LIKE 'HEALTHCARE_STAGE';

ALTER STAGE HEALTHCARE_STAGE REFRESH;

LIST @HEALTHCARE_STAGE;
